### ISSUE TITLE
Reaching end-of-file doesn't stop, results in "MaxBufferSize exceeded. Try increasing the buffer size" error

### ISSUE THREAD

**Issue by zaus** [AndrewRissing/GenericParsing#10]
It seems like there might be a bug when reaching the end of a file, in that reading a block into the buffer ends up with lots of `\0` characters when you get to the end of the file rather than `intCharactersRead` being 0 at the following line:

https://github.com/AndrewRissing/GenericParsing/blob/master/GenericParsing/GenericParser.cs#L1980

**Comment by zaus** [comment]
Seems like [line 1983](https://github.com/AndrewRissing/GenericParsing/blob/master/GenericParsing/GenericParser.cs#L1983) should compare the number of characters read against the possible buffer size (instead of 1) as and EOF/EOS will not fill the buffer completely.

**Comment by AndrewRissing** [comment]
Can you provide any example of the input you've got to ensure that you don't have bad input or a buffer size that's too small?

When checking the number of characters coming back from the buffer, the number of characters returned dictates whether the stream has any more data to read.

If you end up being unable to read from the text reader because you don't have a large enough buffer ```(this.m_intMaxBufferSize - this.m_intStartIndexOfNewData)```, then you've got a buffer size that's too small issue.

Outside of that, if the buffer is large enough and the text reader reads less than one character, then the input stream is out of data.

Let me know and we'll see if we can diagnose it further.

**Comment by zaus** [comment]
I can't provide the specific file (proprietary) but it turns out it's probably something to do with bad input; data was getting read in from a stream and passed as a string to the parser, and it seems like something about the reading and encoding was wrong _sometimes_.  Oh well.

I still don't really understand why the buffer size matters beyond performance, as you should be able to keep reading until there's nothing left to read regardless of whether you're chopping it into 4096 characters at a time or 1 character.  But I'm still working my way through your code, so apologies if I've jumped the gun.  I appreciate your offer for additional diagnostic help.

**Comment by AndrewRissing** [comment]
I don't need that specific of an example, but I'll leave it in your hands from here then.

The buffer size is to ensure that those consuming the file have control over how much memory the library consumes.  I don't want to negatively impact an application by just using a list and blowing out memory when something gets parsed that's poorly formed or malicious.

The buffer is needed to write out the ultimate value that was parsed from the buffer (text qualifiers, etc.).
